version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "nestjs-app"
    ports:
      - "3000:3000"

    depends_on:
      - rabbitmq
networks:
  webnet:
volumes:
  mongodb_data_container:
